package com.github.xiaoxixi.user.dao;

import com.github.xiaoxixi.user.domain.UserAccessToken;

public interface UserAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    int insert(UserAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    int insertSelective(UserAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    UserAccessToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAccessToken record);
}